### ISSUE TITLE
Whitespace in the Firestore document ID

### ISSUE THREAD

**Issue by yamankatby** [meilisearch/firestore-meilisearch#104]
**Description**
If there is a space in the Firestore document id the MeiliSearch record will not be created and nothing logged

**Expected behavior**
A functions log tells that whitespaces not allowd

**Current behavior**
Nothing in the logs

**Screenshots or Logs**
![Screen Shot 2022-09-01 at 14 03 07](https://user-images.githubusercontent.com/35961879/188452162-6f58a5c6-d671-427f-8cbe-e30c65fbc315.png)

**Environment (please complete the following information):**
- OS: [e.g. Debian GNU/Linux]
- Meilisearch version: [e.g. v.0.20.0]
- firestore-meilisearch version: [e.g v0.1.0]

**Comment by bidoubiwa** [comment]
Hey @yamankatby , thanks for raising this :)

Currently, no errors are raised as the extension is not aware an error occurred. Since adding documents in Meilisearch is an [asynchronous task](https://docs.meilisearch.com/learn/advanced/asynchronous_operations.html), to know if the addition was successful we need to check on the task later on. Which this extension does not. 

To still have the knowledge of the error, adding an id validator checking on all the [formatting requirements of a document id](https://docs.meilisearch.com/learn/core_concepts/primary_key.html#formatting-the-document-id) is a good idea. Nonetheless, other task-related errors will remain un-logged and you'll only be aware of it by checking the tasks statuses manually.
