### ISSUE TITLE
Limiting fields for import script

### ISSUE THREAD

**Issue by rkeppner** [meilisearch/firestore-meilisearch#134]
When I configure the Firestore extension, I can indicate which fields I want to index in Meilisearch. However, the [script to import existing documents](https://github.com/meilisearch/firestore-meilisearch/blob/main/guides/IMPORT_EXISTING_DOCUMENTS.md) (`firestore-meilisearch`) doesn't seem to have this option. When I import the existing documents, _all_ fields seem to be indexed.

What's the best way to import existing documents while only indexing certain fields?

**Comment by rkeppner** [comment]
I found one way to do it: set the environment variable `MEILISEARCH_FIELDS_TO_INDEX`. I'm going to assume this just needs to be added to the documentation and submit a PR for that, as soon as I get around to it.

**Comment by bidoubiwa** [comment]
Hey @rkeppner, the issue seems to be that `fieldsToIndex` is not added as a CLI flag here:

https://github.com/meilisearch/firestore-meilisearch/blob/73f00895a1d469893998aa6db083fd51f72bbc68/functions/src/import/config.ts#L14-L20

While your PR does create a work-around, it should be fixed by adding `fieldsToIndex` as a flag.
